version: '3.8'

services:
  db_credit_app:
    image: postgres:16
    container_name: db_credit_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2411
      POSTGRES_DB: db_credit_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: credit-backend
    depends_on:
      db_credit_app:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_credit_app:5432/db_credit_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2411
    ports:
      - "8080:8080"
      
volumes:
  postgres_data: