
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db_credit_app:5432/db_credit_app}
spring.datasource.username=postgres
spring.datasource.password=2411
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.package-to-scan=credit_app_back.app.entity

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

app.client.page-size=10
app.application.page-size=10
app.agreement.page-size=10

server.port=8080