spring.application.name=app

spring.datasource.url=jdbc:postgresql://localhost:5432/db_credit_app
spring.datasource.username=postgres
spring.datasource.password=2411

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate  

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.contexts=dev

server.port=8080

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE